import { assert } from '@apollo/federation-internals';
import { HINTS } from './hints';

const header = `---
title: Federation Hints
sidebar_title: Hints
---

When Apollo Gateway successfully **compose** the schemas provided by your [subgraphs](./subgraphs/) into a **supergraph schema**, it may generate a number of "hints" that bring special attention to parts of the composition that required a non-trivial resolution.
Those hints are mainly informative and usually does not indicate a problem, but are meant as a signal for your to double-check that the result of composition is indeed what was intended. 

This document lists the potential hints that can be generated and a description of why they are generated.
`;

function makeMardownArray(
  headers: string[],
  rows: string[][]
): string {
  const columns = headers.length;
  let out = '| ' + headers.join(' | ') + ' |\n';
  out += '|' + headers.map(_ => '---').join('|') + '|\n';
  for (const row of rows) {
    assert(row.length <= columns, `Row [${row}] has too columns (expect ${columns} but got ${row.length})`);
    const frow = row.length === columns
      ? row
      : row.concat(new Array<string>(columns - row.length).fill(''));
    out += '| ' + frow.join(' | ') + ' |\n'
  }
  return out;
}

const rows = Object.values(HINTS).map(def => [
  '`' + def.code + '`',
  def.description,
]);

const sortRowsByCode = (r1: string[], r2: string[]) => r1[0].localeCompare(r2[0]);

rows.sort(sortRowsByCode);

const hintsSection = `## Hints

The following hints may be generated by composition:

` + makeMardownArray(
  [ 'Code', 'Description' ],
  rows
);

console.log(
  header + '\n\n'
  + hintsSection
);

